[package]
name = "profile"
version = "0.0.1-alpha19"
authors = [ "joelulahanna@gmail.com" ]
edition = "2018"

[lib]
name = "profile"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
profile = {git = "https://github.com/zo-el/hc-zomes", branch = "develop", package = "profile"}
hdk3 = "0"
holo_hash = "0"
hc_utils = "0"
